services:
  app:
    build:
      context: .
      target: ${NODE_ENV:-production}
    environment:
      NODE_ENV: ${NODE_ENV:-production}
      NEXT_PUBLIC_API_URL: ${API_URL}
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      - postgres
    networks:
      - internal

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE-postgres}
      POSTGRES_USER: ${POSTGRES_USERNAME-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD-postgres}
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - internal

volumes:
  postgres:

networks:
  internal:
